name: Playwright Tests to Google Sheets

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright test form
        run: npx playwright test form.spec.js --project=chromium --reporter=json > resultForm.json

      - name: Run Playwright test login
        run: npx playwright test login.spec.js --project=chromium --reporter=json > resultLogin.json

      - name: Upload Playwright form report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-form-report
          path: resultForm.json
          retention-days: 30

      - name: Upload Playwright login report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-login-report
          path: resultLogin.json
          retention-days: 30

      - name: Write Google credentials
        run: |
          mkdir -p scripts
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > scripts/credentials.json

      - name: Report results to Google Sheets
        run: node scripts/reportForm.js
      
      - name: Report results to Google Sheets
        run: node scripts/reportLogin.js