name: "ZAP API Scan CI workflow"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:
  security test:
    name: "Security Testing"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          target: 'http://vbee.vn'    

  advanced-job:
    name: "advanced - Security Testing"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://vbee.vn'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a' 