name: Security Tests

on:
  schedule:
    # Runs every day At 01:00.
    - cron:  '0 2 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://vbee.vn/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'