name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd app
          docker build -t dast-automation-web .

      - name: Run Flask app in Docker
        run: |
          cd app
          docker network create zap-network
          docker run -d --network zap-network --name dast-automation-web dast-automation-web
          sleep 30  # Wait for the application to be ready

      - name: Log in to Docker Hub

        run: |
          echo "1" | docker login -u "cuong" --password-stdin

      - name: Pull OWASP ZAP Docker image
        run: docker pull ictu/zap2docker-weekly

      - name: Start OWASP ZAP scan
        run: |
          sudo chmod -R 777 $(pwd)  # Ensure the directory has the correct permissions
          docker run --network zap-network -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -t http://dast-automation-web:8080 -r zap_report.html || true

      - name: Stop Docker container
        run: |
          docker stop dast-automation-web
          docker rm dast-automation-web
          docker network rm zap-network

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html